import React from 'react';
// import Breadcrumb from '../components/Breadcrumb';

const PrivacyPolicy: React.FC = () => {
  return (
    <div className="min-h-screen bg-white">
      {/* <Breadcrumb currentPage="Privacy Policy" /> */}
      
      <div className="container max-w-6xl mx-auto px-4 py-8">
        <h1 className="text-3xl md:text-4xl font-bold text-gray-800 mb-8">
          Privacy Policy
        </h1>
        
        <div className="bg-white rounded-lg shadow-sm border p-8">
          <div className="prose max-w-none text-gray-700 leading-relaxed space-y-6">
            <p className="text-sm text-gray-600 mb-6">
              <strong>Last updated:</strong> February 07, 2023
            </p>
            
            <p>
              This Privacy Policy describes our policies and procedures for collecting, using, and disclosing your information when you use our services or register as a professional (technician or service provider). It also informs you of your privacy rights and the legal safeguards that apply to you.
            </p>

            <p>
              <strong>PRNV Services</strong> use your personal data to provide and improve the service from both customer and professional (technician/service provider) end. By using the service, you agree to the collection and use of information in accordance with this privacy policy.
            </p>

            <h2 className="text-2xl font-semibold text-blue-700 mt-8 mb-4">Interpretation and Definitions</h2>
            
            <h3 className="text-xl font-semibold text-gray-800 mb-3">Interpretation</h3>
            <p>
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear singular or plural.
            </p>

            <h3 className="text-xl font-semibold text-gray-800 mb-3">Definitions</h3>
            <p className="mb-4">For the purposes of this Privacy Policy:</p>
            
            <div className="bg-gray-50 p-6 rounded-lg">
              <ol className="list-decimal list-inside space-y-2 text-sm">
                <li><strong>Account</strong> means an individual account created for you to access our service or to be a part of our service.</li>
                <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to PRNV Services, 6th floor, Swathi Plaza, Leelanagar, Ameerpet, Hyderabad.</li>
                <li><strong>Cookies</strong> are small files placed on your computer, mobile device, or any other device by a website, containing the details of your browsing history on that website among its many uses.</li>
                <li><strong>Device</strong> means any device that can access the service, such as a computer, a cellphone, or a digital tablet.</li>
                <li><strong>Personal Data</strong> is any information related to an identified or identifiable individual.</li>
                <li><strong>Third-party Social Media Service</strong> refers to any website or social network website through which a user or professional (technician/service provider) can log in or create an account to use the service or be a part of our service.</li>
                <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the service or from the service infrastructure itself (for example, the duration of a page visit).</li>
                <li><strong>Website</strong> refers to PRNV Services, accessible from https://www.prnvservices.com.</li>
                <li><strong>You</strong> mean the individual accessing or using the Service or the Company or other legal entity on behalf of which such individual is accessing or using the service, as applicable. Collecting and using your personal data.</li>
              </ol>
            </div>

            <h2 className="text-2xl font-semibold text-blue-700 mt-8 mb-4">Types of Data Collected</h2>
            
            <h3 className="text-xl font-semibold text-gray-800 mb-3">Personal Data</h3>
            
            <div className="space-y-6">
              <div className="bg-blue-50 p-6 rounded-lg border-l-4 border-blue-400">
                <h4 className="font-semibold text-blue-800 mb-3">For Customers:</h4>
                <p className="text-sm mb-3">We may ask You to provide Us with personally identifiable information that can be used to contact or identify You while using our service. Personally identifiable information may include, but is not limited to, the following:</p>
                <ul className="list-disc list-inside space-y-1 text-sm">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Address, State, Province, ZIP/Postal code, City</li>
                  <li>Usage Data</li>
                </ul>
              </div>

              <div className="bg-green-50 p-6 rounded-lg border-l-4 border-green-400">
                <h4 className="font-semibold text-green-800 mb-3">For Professional (Technician/Service Provider):</h4>
                <p className="text-sm mb-3">The Professional who choose to use our services as a Professional (Technician/Service Provider), we will ask you for some personal information that will allow us to get in touch with you or identify you. This private information includes:</p>
                <ul className="list-disc list-inside space-y-1 text-sm">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>2 Referral Mobile Number</li>
                  <li>Current Address & Permanent Address</li>
                  <li>Aadhar Card, Voter Card, or Driving License</li>
                  <li>Your Passport Size Photo for Profile</li>
                  <li>Usage Data</li>
                </ul>
                <p className="text-sm mt-3"><strong>Note:</strong> This personal data is not limited; it is unlimited and subject to periodic changes.</p>
              </div>
            </div>

            <h3 className="text-xl font-semibold text-gray-800 mb-3 mt-8">Usage Data</h3>
            <p>
              Usage Data is collected automatically when using the services.
            </p>
            <p>
              Usage Data may include information such as Your Device's Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our service that You visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
            <p>
              When you access the service by or through a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device you use, your mobile device's unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
            </p>
            <p>
              We may also collect information that your browser sends whenever you visit our service or access the service through a mobile device.
            </p>

            <h3 className="text-xl font-semibold text-gray-800 mb-3 mt-8">Information from Third-Party Social Media Services</h3>
            <p>
              The Company allows you to create an account and log in to use the services through the following Third-party Social Media Services:
            </p>
            <ol className="list-decimal list-inside ml-6 space-y-2">
              <li>Gmail</li>
              <li>Facebook</li>
            </ol>
            <p>
              When you decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with your Third-Party Social Media Service's account, such as your name, email address, activities, or contact list associated with that account.
            </p>
            <p>
              You may also have the option of sharing additional information with the Company through your Third-Party Social Media Service's account. If you choose to provide such information and Personal Data during registration or otherwise, you are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.
            </p>

            <h2 className="text-2xl font-semibold text-blue-700 mt-8 mb-4">Tracking Technologies and Cookies</h2>
            <p>
              We use Cookies and similar tracking technologies to track the activity on our service and store certain information. Tracking technologies are beacons, tags, and scripts to collect and track information and improve and analyze our service. The technologies We use may include:
            </p>
            <ol className="list-decimal list-inside ml-6 space-y-2">
              <li><strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on your device. You can instruct your browser to refuse all Cookies or to indicate when a cookie is being sent. However, if you do not accept Cookies, You may not be able to use some parts of our service. Unless you have adjusted your browser setting so it will refuse cookies, our service may use Cookies.</li>
              <li><strong>Web Beacons:</strong> Certain sections of our service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
            </ol>

            <h3 className="text-xl font-semibold text-gray-800 mb-3 mt-8">We use both Sessions and Persistent Cookies for the purposes set out below:</h3>
            
            <div className="bg-gray-50 p-6 rounded-lg">
              <h4 className="font-semibold text-gray-800 mb-3">Necessary / Essential Cookies</h4>
              <p><strong>Type:</strong> Session Cookies</p>
              <p><strong>Administered by:</strong> Us</p>
              <p><strong>Purpose:</strong> These Cookies are essential to provide you with services available through the website and to enable you to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide you with those services.</p>
              
              <h4 className="font-semibold text-gray-800 mb-3 mt-6">Cookies Policy / Notice Acceptance Cookies</h4>
              <p><strong>Type:</strong> Persistent Cookies</p>
              <p><strong>Administered by:</strong> Us</p>
              <p><strong>Purpose:</strong> These Cookies identify if users have accepted the use of cookies on the Website.</p>
              
              <h4 className="font-semibold text-gray-800 mb-3 mt-6">Functionality Cookies</h4>
              <p><strong>Type:</strong> Persistent Cookies</p>
              <p><strong>Administered by:</strong> Us</p>
              <p><strong>Purpose:</strong> These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
            </div>

            <h2 className="text-2xl font-semibold text-blue-700 mt-8 mb-4">Use of Your Personal Data</h2>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ol className="list-decimal list-inside ml-6 space-y-2">
              <li>To provide and maintain our Service, including monitoring the usage of our Service.</li>
              <li>To Manage Your Account, to manage Your registration as a user of the Service or as a professional (technician/service provider). The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user or a professional (technician/service provider).</li>
              <li>For the performance of a professional (technician/service provider) and undertaking of the services you book through our website.</li>
              <li>To Contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products, or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
              <li>To provide You with news, special offers, and general information about other goods, services, and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
              <li>To manage Your requests means to attend and manage your requests to us.</li>
              <li>For other purposes means we may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and evaluating and improving our Service, marketing, and your experience.</li>
            </ol>

            <h3 className="text-xl font-semibold text-gray-800 mb-3 mt-8">We may share Your personal information in the following situations:</h3>
            <ol className="list-decimal list-inside ml-6 space-y-2">
              <li><strong>With Professionals (Technicians/Service Providers):</strong> We may give professionals (technicians/service providers) access to your contact number, so they can get in touch with you about the services you've requested.</li>
              <li><strong>With Affiliates:</strong> We may share Your information with Our affiliates, which will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners, or other companies that We control or that are under common control with Us.</li>
              <li><strong>With business partners:</strong> We may share Your information with Our business partners to offer You certain products, services, or promotions.</li>
              <li><strong>With other users:</strong> when You share personal information or otherwise interact in public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures, and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.</li>
              <li><strong>With Your consent:</strong> We may disclose Your personal information for any other purpose with Your consent.</li>
            </ol>

            <h2 className="text-2xl font-semibold text-blue-700 mt-8 mb-4">Retention of Your Personal Data</h2>
            <p>
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
            </p>
            <p>
              The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or improve the functionality of Our Service. We are legally obligated to retain this data for longer.
            </p>

            <h2 className="text-2xl font-semibold text-blue-700 mt-8 mb-4">Transfer of Your Personal Data</h2>
            <p>
              Your information, including Personal Data, is processed at the Company's operating offices and other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country, or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
            </p>
            <p>
              Your consent to this Privacy Policy, followed by Your submission of such information, represents Your agreement to that transfer.
            </p>
            <p>
              The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy, and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place, including the security of Your data and other personal information.
            </p>

            <h2 className="text-2xl font-semibold text-blue-700 mt-8 mb-4">Delete Your Personal Data</h2>
            <p>
              You have the right to delete or request that We assist in deleting the Personal Data We have collected about You.
            </p>
            <p>
              Our Service may allow You to delete certain information about You from within the Service. You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information you have provided.
            </p>
            <p>
              Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
            </p>

            <h2 className="text-2xl font-semibold text-blue-700 mt-8 mb-4">Disclosure of Your Personal Data</h2>
            <h3 className="text-xl font-semibold text-gray-800 mb-3">Business Transactions</h3>
            <p>
              If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
            </p>

            <h3 className="text-xl font-semibold text-gray-800 mb-3">Law Enforcement</h3>
            <p>
              Under certain circumstances, the Company may be required to disclose Your Personal Data if required by law or in response to valid requests by public authorities (e.g., a court or a government agency).
            </p>

            <h3 className="text-xl font-semibold text-gray-800 mb-3">Other legal requirements</h3>
            <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
            <ol className="list-decimal list-inside ml-6 space-y-2">
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
              <li>Protect the personal safety of Users of the Service or the public</li>
              <li>Protect against legal liability</li>
            </ol>

            <h2 className="text-2xl font-semibold text-blue-700 mt-8 mb-4">Security of Your Personal Data</h2>
            <p>
              The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>

            <h2 className="text-2xl font-semibold text-blue-700 mt-8 mb-4">Reservation of Rights</h2>
            <p>
              We reserve the right to request that you remove all links or any particular link to our website. You approve of immediately removing all links to our website upon request. We also reserve the right to amend these terms and conditions and its linking policy at any time. By continuously linking to our website, you agree to be bound to and follow these terms and conditions.
            </p>

            <h2 className="text-2xl font-semibold text-blue-700 mt-8 mb-4">Links to Other Websites</h2>
            <p>
              Our Service may contain links to other websites that we do not operate. If You click on a third-party link, You will be directed to that third-party's site. We strongly advise you to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.
            </p>

            <h2 className="text-2xl font-semibold text-blue-700 mt-8 mb-4">Changes to this Privacy Policy</h2>
            <p>
              We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will inform you via email and/or a prominent notice on our service before the change becomes effective and update the "Last updated" date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. This Privacy Policy changes are effective when posted on this page.
            </p>

            <h2 className="text-2xl font-semibold text-blue-700 mt-8 mb-4">Payment Policy</h2>
            <h3 className="text-xl font-semibold text-gray-800 mb-3">Customer:</h3>
            <p>
              There is no online payment process for customers who book services on our website. Because payment is made only after the work is completed directly to the professional (technician/service provider). There is no refund for the amount paid to the service provider.
            </p>
            
            <div className="bg-yellow-50 p-6 rounded-lg border-l-4 border-yellow-400">
              <h4 className="font-semibold text-yellow-800 mb-3">Note:</h4>
              <ol className="list-decimal list-inside space-y-2 text-sm">
                <li>PRNV Services is not involved in any payment between the customer and professional (technician/service provider).</li>
                <li>Customer should make payment to the professional (technician/service provider) after work is done.</li>
                <li>After work is done, customers should mention all the required fields, including work started, work amount paid, rating, and reviews on the service profile page. These details will be tracked for different processes like providing 1 week of work guarantee.</li>
                <li>The amount paid to a professional (technician/service provider) after work is not refundable.</li>
                <li>To get compensation from the professional (technician/service provider) for any damage during work as per the agreement with PRNV Services, the customer should mention the total work amount accepted, work started, work completed, the total amount paid, rating & reviews.</li>
              </ol>
            </div>

            <h3 className="text-xl font-semibold text-gray-800 mb-3 mt-8">Professional (Technician/Service Provider):</h3>
            <p>
              The Professional (Technician/Service Provider) has to pay a monthly fee by enrolling in one of four plans. When a professional (technician/service provider) subscribes to any of these plans, the fee is non-refundable. During the payment process, the details of your cards or UPI will be safely stored with us, making your payment safe and secure.
            </p>
            
            <div className="bg-yellow-50 p-6 rounded-lg border-l-4 border-yellow-400">
              <h4 className="font-semibold text-yellow-800 mb-3">Note:</h4>
              <ol className="list-decimal list-inside space-y-2 text-sm">
                <li>Professionals (Technicians/Service Providers) can change the pin code during the Time of renewal. He can't change the pincode in the ongoing plan.</li>
                <li>Professionals (Technicians/Service Providers) can change the plan only after the completion of an ongoing plan for 30 days. And the base fare may vary according to the new plan you choose.</li>
                <li>Professionals (Technicians/Service Providers) must renew the plan in 30 days. On failing, the profile will not be accessible to the customers. And the next renewal amount may change according to the fares of that time.</li>
                <li>The professional (technician/service provider) profile in the searched category will be displayed based on seniority, like first come, first serve. Professionals (Technicians/Service Providers) will lose the seniority benefits if they fail to renew on time.</li>
              </ol>
            </div>
          </div>
        </div>
      </div>
      
    </div>
  );
};

export default PrivacyPolicy;